parameters:
#    babaganoush_flotr2.example.class: Babaganoush\Flotr2Bundle\Example

services:
#    Babaganoush_flotr2.example:
#        class: %2levelsabove_flotr2.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
